#!/usr/bin/env bash
# =============================================================================
# xcross Swift Runner Spike — de-risk experiment (S0)
# =============================================================================
# Run INSIDE the xcross-compose amd64 container (or any linux/amd64 host with
# swift 6.x, llvm-18 ld64.lld, konanc 2.4.0, Gradle, JDK 21, Darwin SDK).
#
# Purpose: pin the 5 Linux swiftc unknowns and produce an arm64 Runner binary
# from examples/example_cmp. Outputs loud PASS/FAIL banners per unknown plus
# a SPIKE SUMMARY with the EXACT working swiftc flag line.
#
# Unknowns:
#   U1  Does swiftc accept -use-ld=<ld64.lld>?  (linker injection)
#   U2  Does SwiftUI compile against the Darwin iOS SDK from Linux?
#   U3  Does -Xcc -isysroot help or break compilation?
#   U4  Is the output binary a valid arm64 Mach-O (not x86_64)?
#   U5  Does Runner hard-require @rpath/libswift*.dylib? (needs SwiftSupport/)
#
# Expected env (defaults shown, override as needed):
#   DARWIN_SDK     ~/.swiftpm/swift-sdks/darwin.artifactbundle
#   LX_KN          /opt/konan/kotlin-native-prebuilt-linux-x86_64-2.4.0
#   KONAN_DATA_DIR /opt/konan
#   XCROSS_LD64LLD /usr/lib/llvm-18/bin/ld64.lld
#   WORKSPACE      /opt/xcross-src  (xcross repo root for dart run jar patcher)
#
# NOTE: Run this script BEFORE trusting the swiftc flags in the packer.
#       The exact working invocation is printed in the SPIKE SUMMARY.
# =============================================================================
set -euxo pipefail

PASS="PASS"
FAIL="FAIL"

# ── result vars ──
FWK_RESULT="$FAIL"
SWIFT_PRIMARY_RESULT="$FAIL"
U1_RESULT="N/A"
U2_RESULT="N/A"
U3_RESULT="N/A"
U4_RESULT="$FAIL"
U5_RESULT="UNKNOWN"
WORKING_SWIFTC_CMD=""

# ── env resolution ────────────────────────────────────────────────────────────
DARWIN_SDK="${DARWIN_SDK:-$HOME/.swiftpm/swift-sdks/darwin.artifactbundle}"
LX_KN="${LX_KN:-/opt/konan/kotlin-native-prebuilt-linux-x86_64-2.4.0}"
KONAN_DATA_DIR="${KONAN_DATA_DIR:-/opt/konan}"
XCROSS_LD64LLD="${XCROSS_LD64LLD:-/usr/lib/llvm-18/bin/ld64.lld}"
# WORKSPACE: xcross source root for 'dart run' jar patcher.
# In the container xcross-src is baked at /opt/xcross-src.
# In CI GITHUB_WORKSPACE is set; outside CI fall back to the container path.
WORKSPACE="${GITHUB_WORKSPACE:-/opt/xcross-src}"

# iPhoneOS SDK — first versioned dir wins.
IPHONE_SDK=""
for _sdk in "$DARWIN_SDK"/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS*.sdk; do
  if [[ -d "$_sdk" ]]; then
    IPHONE_SDK="$_sdk"
    break
  fi
done

# Swift resource dir (stdlib overlays + clang headers bundled with Swift SDK).
SWIFT_RES="$DARWIN_SDK/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift"

# Gradle module containing the iosArm64 target.
MODULE="sharedLogic"
BASE_NAME="SharedLogic"

echo ""
echo "===== SPIKE CONFIG ====="
echo "DARWIN_SDK:       $DARWIN_SDK"
echo "IPHONE_SDK:       ${IPHONE_SDK:-NOT FOUND}"
echo "SWIFT_RES:        $SWIFT_RES"
echo "LX_KN:            $LX_KN"
echo "KONAN_DATA_DIR:   $KONAN_DATA_DIR"
echo "XCROSS_LD64LLD:   $XCROSS_LD64LLD"
echo "WORKSPACE:        $WORKSPACE"
echo "MODULE/BASE_NAME: $MODULE / $BASE_NAME"
echo "========================"

# ── A. Copy example_cmp to writable temp dir ─────────────────────────────────
echo ""
echo "===== SETUP: Copy examples/example_cmp → /tmp/cmp_spike ====="
CMP_DIR=/tmp/cmp_spike
rm -rf "$CMP_DIR"
# Support both: running from repo root or from inside the container.
if [[ -d "$WORKSPACE/examples/example_cmp" ]]; then
  cp -r "$WORKSPACE/examples/example_cmp" "$CMP_DIR"
elif [[ -d "examples/example_cmp" ]]; then
  cp -r "examples/example_cmp" "$CMP_DIR"
else
  echo "::error::examples/example_cmp not found. Run from repo root or set WORKSPACE."
  exit 1
fi
chmod +x "$CMP_DIR/gradlew"
ls -la "$CMP_DIR/"

OUTDIR=/tmp/cmpout
rm -rf "$OUTDIR"
mkdir -p "$OUTDIR"

# ── PREREQUISITE: HostManager jar patch ──────────────────────────────────────
# Replicates ComposePacker Stage 1 via dart run patchKotlinNativeJar().
echo ""
echo "===== PREREQUISITE: HostManager jar patch ====="

JAR_PATCHED=false
JAR_PATH="$(find "$LX_KN" -name 'kotlin-native-compiler-embeddable.jar' -print -quit 2>/dev/null || true)"

if [[ -z "$JAR_PATH" ]]; then
  echo "WARNING: kotlin-native-compiler-embeddable.jar not found under $LX_KN"
  echo "  konanc will hit HostManager gate — continuing to capture the error."
else
  echo "Found jar: $JAR_PATH"
  PATCH_HELPER="$WORKSPACE/bin/spike_patch_jar.dart"
  cat > "$PATCH_HELPER" << 'DART_EOF'
// Runtime-generated by scripts/swift-runner-spike.sh — not committed.
import 'package:xcross/src/build/host_manager_patcher.dart';
void main(List<String> args) {
  if (args.isEmpty) { print('Usage: spike_patch_jar.dart <jar>'); return; }
  final result = patchKotlinNativeJar(args[0]);
  print(result ? 'PATCH_APPLIED: ${args[0]}' : 'PATCH_SKIPPED: ${args[0]}');
}
DART_EOF
  PATCH_OUT=""
  if PATCH_OUT=$(cd "$WORKSPACE" && dart run bin/spike_patch_jar.dart "$JAR_PATH" 2>&1); then
    echo "Jar patch result: $PATCH_OUT"
    JAR_PATCHED=true
  else
    echo "WARNING: dart jar patcher failed:"
    echo "$PATCH_OUT"
    echo "  Continuing with un-patched jar; konanc HostManager error = the finding."
  fi
  rm -f "$PATCH_HELPER"
fi
echo "JAR_PATCHED=$JAR_PATCHED"

# ── PREREQUISITE: ld wrapper + Apple shims ────────────────────────────────────
# Mirrors ComposePacker Stage 3+4 for konanc's framework link probes.
echo ""
echo "===== PREREQUISITE: ld wrapper + Apple shims ====="

SPIKE_UNI=/tmp/swift-spike-uni
mkdir -p "$SPIKE_UNI/usr/bin"

# ld wrapper — expand XCROSS_LD64LLD at write time so the wrapper is self-contained.
cat > "$SPIKE_UNI/usr/bin/ld" << LDEOF
#!/bin/bash
exec "${XCROSS_LD64LLD}" "\$@"
LDEOF
chmod +x "$SPIKE_UNI/usr/bin/ld"

sudo mkdir -p /usr/libexec
{ echo '#!/bin/bash'; echo 'echo "16.0"'; echo 'exit 0'; } \
  | sudo tee /usr/libexec/PlistBuddy > /dev/null
sudo chmod +x /usr/libexec/PlistBuddy

{ echo "#!/bin/bash"
  echo "printf '%s/Developer\n' '${DARWIN_SDK}'"
  echo "exit 0"
} | sudo tee /usr/local/bin/xcode-select > /dev/null
sudo chmod +x /usr/local/bin/xcode-select

{ echo '#!/bin/bash'
  echo 'echo "[xcrun-shim] $*" >> /tmp/xcrun-swift-spike.log'
  echo 'case "$*" in'
  echo '  "xcodebuild -version"|"-version") echo "Xcode 16.0"; echo "Build version 16A242d" ;;'
  echo "  \"-f ld\"|\"--find ld\") echo '${SPIKE_UNI}/usr/bin/ld' ;;"
  echo '  "-f clang"|"--find clang") echo /usr/bin/clang ;;'
  echo '  "-f clang++"|"--find clang++") echo /usr/bin/clang++ ;;'
  echo '  "-f strip"|"--find strip") echo /usr/bin/strip ;;'
  echo '  "-f ar"|"--find ar") echo /usr/bin/ar ;;'
  echo '  "-f nm"|"--find nm") echo /usr/bin/nm ;;'
  echo "  \"-f dsymutil\"|\"--find dsymutil\") echo '${DARWIN_SDK}/toolset/bin/dsymutil' ;;"
  echo "  \"--sdk iphoneos --show-sdk-path\") echo '${IPHONE_SDK}' ;;"
  echo "  \"--sdk macosx --show-sdk-path\") echo '${IPHONE_SDK}' ;;"
  echo '  "simctl list runtimes -j") echo "{}" ;;'
  echo '  *) echo /usr/bin/false ;;'
  echo 'esac'
  echo 'exit 0'
} | sudo tee /usr/local/bin/xcrun > /dev/null
sudo chmod +x /usr/local/bin/xcrun
echo "Apple shims installed"

# ── PREREQUISITE: konan.properties (SPIKE_PATCH block) ───────────────────────
KONAN_PROPS="$LX_KN/konan/konan.properties"
if [[ -f "$KONAN_PROPS" ]] && ! grep -q 'SWIFT_SPIKE_PATCH' "$KONAN_PROPS"; then
  cat >> "$KONAN_PROPS" << PROPS

# SWIFT_SPIKE_PATCH — swift-runner-spike.sh: linux_x64 → ios_arm64 stubs.
targetSysRoot.ios_arm64 = ${IPHONE_SDK}
targetToolchain.linux_x64-ios_arm64 = ${SPIKE_UNI}/usr
additionalToolsDir.ios_arm64 = ${SPIKE_UNI}/usr
linker.linux_x64-ios_arm64 = ${SPIKE_UNI}/usr/bin/ld
PROPS
  echo "konan.properties: SWIFT_SPIKE_PATCH appended"
fi

# ── GRADLE: compile iosArm64 klib ────────────────────────────────────────────
echo ""
echo "===== GRADLE: :$MODULE:compileKotlinIosArm64 (cross-compile flag) ====="

KLIB_PATH="$CMP_DIR/$MODULE/build/classes/kotlin/iosArm64/main/klib/$MODULE"
GRADLE_EXIT=0
(
  cd "$CMP_DIR"
  ./gradlew ":$MODULE:compileKotlinIosArm64" \
    -Pkotlin.native.enableKlibsCrossCompilation=true \
    --no-daemon \
    --stacktrace \
    2>&1
) || GRADLE_EXIT=$?

if [[ $GRADLE_EXIT -ne 0 ]]; then
  echo "===== GRADLE: FAILED (exit=$GRADLE_EXIT; JAR_PATCHED=$JAR_PATCHED) ====="
  echo "Cannot continue to framework or Swift build without klib."
  # Still attempt the rest so the summary captures all findings.
  KLIB_PATH=""
else
  if [[ -e "$KLIB_PATH" ]]; then
    echo "klib found: $KLIB_PATH"
  else
    echo "WARNING: gradle ok but klib not at expected path: $KLIB_PATH"
    find "$CMP_DIR/$MODULE/build" -maxdepth 7 -type d 2>/dev/null | head -40 || true
    KLIB_PATH=""
  fi
fi

# ── DEPS ENUM ─────────────────────────────────────────────────────────────────
echo ""
echo "===== DEPS ENUM: iosArm64 compilation dep klibs ====="

cat << 'INIT_EOF' | sed "s/MODULE_NAME/${MODULE}/g" > /tmp/swift-spike-deps.init.gradle.kts
// Generated by scripts/swift-runner-spike.sh — reflection-based, proven working.
allprojects {
    if (name != "MODULE_NAME") return@allprojects
    tasks.register("dumpIosDeps") {
        dependsOn("compileKotlinIosArm64")
        doLast {
            val kotlinExt = project.extensions.findByName("kotlin")
                ?: error("[spike] no 'kotlin' extension on '$name'")
            val targets = kotlinExt.javaClass.getMethod("getTargets").invoke(kotlinExt)
            val findByName = targets.javaClass.methods.first { it.name == "findByName" }
            val target = findByName.invoke(targets, "iosArm64")
                ?: error("[spike] no iosArm64 target in '$name'")
            val compilations = target.javaClass.getMethod("getCompilations").invoke(target)
            val getByName = compilations.javaClass.methods
                .first { it.name == "getByName" && it.parameterCount == 1 }
            val main = getByName.invoke(compilations, "main")
            val cdf = main.javaClass.methods
                .first { it.name == "getCompileDependencyFiles" }.invoke(main)
            @Suppress("UNCHECKED_CAST")
            val files = cdf.javaClass.getMethod("getFiles").invoke(cdf) as Set<java.io.File>
            val out = java.io.File("/tmp/cmp-deps.txt")
            out.writeText(files.joinToString("\n") { it.absolutePath })
            println("[spike:dumpIosDeps] wrote ${files.size} entries to ${out.absolutePath}")
        }
    }
}
INIT_EOF

DEPS_EXIT=0
(
  cd "$CMP_DIR"
  ./gradlew ":$MODULE:dumpIosDeps" \
    --init-script /tmp/swift-spike-deps.init.gradle.kts \
    --no-daemon \
    --no-configuration-cache \
    --console=plain \
    --stacktrace \
    2>&1
) || DEPS_EXIT=$?

LIBARGS=()
if [[ $DEPS_EXIT -eq 0 && -f /tmp/cmp-deps.txt ]]; then
  echo "dep list:"
  cat /tmp/cmp-deps.txt
  while IFS= read -r f; do
    case "$f" in
      *.klib) [[ -e "$f" ]] && LIBARGS+=(-library "$f") || echo "WARNING: missing klib: $f" ;;
    esac
  done < /tmp/cmp-deps.txt
  echo "LIBARGS count: ${#LIBARGS[@]}"
else
  echo "WARNING: dep enum failed (exit=$DEPS_EXIT) — konanc will run without -library args"
fi

# ── KONANC: SharedLogic.framework ─────────────────────────────────────────────
echo ""
echo "===== KONANC: -Xinclude → $BASE_NAME.framework ====="

FWK_DIR="$OUTDIR/${BASE_NAME}.framework"
KONANC_EXIT=1

if [[ -z "$IPHONE_SDK" ]]; then
  echo "SKIP: IPHONE_SDK not resolved — Darwin SDK missing."
elif [[ -z "$KLIB_PATH" ]]; then
  echo "SKIP: klib not available (gradle failed above)."
else
  mkdir -p "$OUTDIR"
  "$LX_KN/bin/konanc" \
    -target ios_arm64 \
    -p framework \
    -Xadd-light-debug=disable \
    -Xbinary="bundleId=com.example.cmpspike" \
    -Xoverride-konan-properties="targetSysRoot.ios_arm64=${IPHONE_SDK};linker.linux_x64-ios_arm64=${XCROSS_LD64LLD};targetToolchain.linux_x64-ios_arm64=${DARWIN_SDK}/toolset" \
    -Xinclude="$KLIB_PATH" \
    "${LIBARGS[@]}" \
    -o "$OUTDIR/$BASE_NAME" \
    2>&1 || KONANC_EXIT=$?

  if [[ -d "$FWK_DIR" ]]; then
    echo "Framework produced: $FWK_DIR"
    ls -la "$FWK_DIR/"
    FWK_RESULT="$PASS"
    KONANC_EXIT=0
  else
    echo "WARNING: konanc finished but $FWK_DIR not found"
    ls -la "$OUTDIR/" 2>/dev/null || true
  fi
fi
echo "===== FRAMEWORK: $FWK_RESULT ====="

# ── Collect Swift sources ──────────────────────────────────────────────────────
echo ""
echo "===== U-SWIFT: compile Swift Runner ====="

# Gather Swift source files (exclude Preview Content).
SWIFT_SRCS=()
while IFS= read -r sf; do
  SWIFT_SRCS+=("$sf")
done < <(find "$CMP_DIR/iosApp/iosApp" -name '*.swift' \
           ! -path '*/Preview Content/*' \
           ! -path '*/PreviewContent/*' \
           | sort)

echo "Swift sources (${#SWIFT_SRCS[@]}):"
printf '  %s\n' "${SWIFT_SRCS[@]}"

if [[ ${#SWIFT_SRCS[@]} -eq 0 ]]; then
  echo "::error::No Swift sources found under $CMP_DIR/iosApp/iosApp/"
  SWIFT_PRIMARY_RESULT="$FAIL (no sources)"
  U4_RESULT="$FAIL (no sources)"
fi

# ── tools-directory wrapper (needed for U1 retry) ────────────────────────────
SWIFT_TOOLS_DIR=/tmp/swift-spike-tools
mkdir -p "$SWIFT_TOOLS_DIR"
cat > "$SWIFT_TOOLS_DIR/ld" << LDEOF
#!/bin/bash
exec "${XCROSS_LD64LLD}" "\$@"
LDEOF
chmod +x "$SWIFT_TOOLS_DIR/ld"

# ── Primary swiftc attempt ────────────────────────────────────────────────────
echo ""
echo "--- Primary swiftc attempt (-use-ld=) ---"

PRIMARY_CMD=(
  swiftc
  -sdk "$IPHONE_SDK"
  -target arm64-apple-ios15.0
  -resource-dir "$SWIFT_RES"
  -F "$OUTDIR"
  -framework "$BASE_NAME"
  -parse-as-library
  -module-cache-path /tmp/swift-mc
  "-use-ld=$XCROSS_LD64LLD"
  -Xfrontend -enable-cross-import-overlays
  -Xlinker -rpath -Xlinker "@executable_path/Frameworks"
  "${SWIFT_SRCS[@]}"
  -o "$OUTDIR/Runner"
)

PRIMARY_EXIT=0
rm -f "$OUTDIR/Runner"
mkdir -p /tmp/swift-mc

if [[ ${#SWIFT_SRCS[@]} -gt 0 && "$FWK_RESULT" == "$PASS" ]]; then
  echo "Running: ${PRIMARY_CMD[*]}"
  "${PRIMARY_CMD[@]}" 2>&1 | tee /tmp/swift-primary.log || PRIMARY_EXIT=$?
  echo ""
  echo "Primary swiftc exit: $PRIMARY_EXIT"

  if [[ $PRIMARY_EXIT -eq 0 && -f "$OUTDIR/Runner" ]]; then
    SWIFT_PRIMARY_RESULT="$PASS (primary -use-ld= worked)"
    U1_RESULT="$PASS (-use-ld= accepted)"
    WORKING_SWIFTC_CMD="${PRIMARY_CMD[*]}"
    echo "===== U-SWIFT PRIMARY: $PASS ====="
  else
    # Diagnose failure type.
    if grep -qi "unknown.*argument.*use-ld\|invalid.*use-ld\|unrecognized.*use-ld" /tmp/swift-primary.log 2>/dev/null; then
      U1_RESULT="$FAIL (-use-ld= not supported — trying -tools-directory)"
    else
      U1_RESULT="$PASS (-use-ld= accepted but build failed for other reason)"
    fi
    echo "Primary failed; diagnosing... U1_RESULT=$U1_RESULT"

    # ── Retry U1: -tools-directory instead of -use-ld= ─────────────────────
    echo ""
    echo "--- Retry U1: -tools-directory $SWIFT_TOOLS_DIR ---"
    RETRY1_CMD=(
      swiftc
      -sdk "$IPHONE_SDK"
      -target arm64-apple-ios15.0
      -resource-dir "$SWIFT_RES"
      -F "$OUTDIR"
      -framework "$BASE_NAME"
      -parse-as-library
      -module-cache-path /tmp/swift-mc
      -tools-directory "$SWIFT_TOOLS_DIR"
      -Xfrontend -enable-cross-import-overlays
      -Xlinker -rpath -Xlinker "@executable_path/Frameworks"
      "${SWIFT_SRCS[@]}"
      -o "$OUTDIR/Runner"
    )
    RETRY1_EXIT=0
    rm -f "$OUTDIR/Runner"
    echo "Running: ${RETRY1_CMD[*]}"
    "${RETRY1_CMD[@]}" 2>&1 | tee /tmp/swift-retry1.log || RETRY1_EXIT=$?
    echo "Retry1 exit: $RETRY1_EXIT"

    if [[ $RETRY1_EXIT -eq 0 && -f "$OUTDIR/Runner" ]]; then
      SWIFT_PRIMARY_RESULT="$PASS (retry1: -tools-directory worked)"
      U1_RESULT="$FAIL (-use-ld= rejected; -tools-directory WORKS)"
      WORKING_SWIFTC_CMD="${RETRY1_CMD[*]}"
      echo "===== U-SWIFT RETRY1: $PASS ====="
    else
      # ── Retry U2: add -disable-modules-validate-system-headers ─────────────
      # Needed if SwiftUI import fails with "overlapping conformances" or module
      # validation errors against the Linux system headers.
      echo ""
      echo "--- Retry U2: add -Xfrontend -disable-modules-validate-system-headers ---"
      RETRY2_CMD=(
        swiftc
        -sdk "$IPHONE_SDK"
        -target arm64-apple-ios15.0
        -resource-dir "$SWIFT_RES"
        -F "$OUTDIR"
        -framework "$BASE_NAME"
        -parse-as-library
        -module-cache-path /tmp/swift-mc
        -tools-directory "$SWIFT_TOOLS_DIR"
        -Xfrontend -enable-cross-import-overlays
        -Xfrontend -disable-modules-validate-system-headers
        -Xlinker -rpath -Xlinker "@executable_path/Frameworks"
        "${SWIFT_SRCS[@]}"
        -o "$OUTDIR/Runner"
      )
      RETRY2_EXIT=0
      rm -f "$OUTDIR/Runner"
      echo "Running: ${RETRY2_CMD[*]}"
      "${RETRY2_CMD[@]}" 2>&1 | tee /tmp/swift-retry2.log || RETRY2_EXIT=$?
      echo "Retry2 exit: $RETRY2_EXIT"

      if [[ $RETRY2_EXIT -eq 0 && -f "$OUTDIR/Runner" ]]; then
        SWIFT_PRIMARY_RESULT="$PASS (retry2: +disable-modules-validate-system-headers)"
        U2_RESULT="$PASS (-disable-modules-validate-system-headers REQUIRED)"
        WORKING_SWIFTC_CMD="${RETRY2_CMD[*]}"
        echo "===== U-SWIFT RETRY2: $PASS ====="
      else
        # ── Retry U3: add -Xcc -isysroot ───────────────────────────────────
        echo ""
        echo "--- Retry U3: add -Xcc -isysroot \$IPHONE_SDK ---"
        RETRY3_CMD=(
          swiftc
          -sdk "$IPHONE_SDK"
          -target arm64-apple-ios15.0
          -resource-dir "$SWIFT_RES"
          -F "$OUTDIR"
          -framework "$BASE_NAME"
          -parse-as-library
          -module-cache-path /tmp/swift-mc
          -tools-directory "$SWIFT_TOOLS_DIR"
          -Xfrontend -enable-cross-import-overlays
          -Xfrontend -disable-modules-validate-system-headers
          -Xcc "-isysroot" -Xcc "$IPHONE_SDK"
          -Xlinker -rpath -Xlinker "@executable_path/Frameworks"
          "${SWIFT_SRCS[@]}"
          -o "$OUTDIR/Runner"
        )
        RETRY3_EXIT=0
        rm -f "$OUTDIR/Runner"
        echo "Running: ${RETRY3_CMD[*]}"
        "${RETRY3_CMD[@]}" 2>&1 | tee /tmp/swift-retry3.log || RETRY3_EXIT=$?
        echo "Retry3 exit: $RETRY3_EXIT"

        if [[ $RETRY3_EXIT -eq 0 && -f "$OUTDIR/Runner" ]]; then
          SWIFT_PRIMARY_RESULT="$PASS (retry3: +-Xcc -isysroot)"
          U3_RESULT="$PASS (-Xcc -isysroot REQUIRED)"
          WORKING_SWIFTC_CMD="${RETRY3_CMD[*]}"
          echo "===== U-SWIFT RETRY3: $PASS ====="
        else
          SWIFT_PRIMARY_RESULT="$FAIL (all swiftc variants failed)"
          U3_RESULT="$FAIL (even +isysroot failed)"
          echo ""
          echo "All swiftc retries exhausted. Logs:"
          echo "--- primary ---"; cat /tmp/swift-primary.log 2>/dev/null || true
          echo "--- retry1  ---"; cat /tmp/swift-retry1.log 2>/dev/null || true
          echo "--- retry2  ---"; cat /tmp/swift-retry2.log 2>/dev/null || true
          echo "--- retry3  ---"; cat /tmp/swift-retry3.log 2>/dev/null || true
        fi
      fi

      # U2: if we never needed it, note it.
      if [[ "$U2_RESULT" == "N/A" ]]; then
        U2_RESULT="NOT_NEEDED (build succeeded without it in earlier retry)"
      fi
    fi
  fi
else
  echo "SKIP: swiftc not attempted (framework missing or no sources)."
  SWIFT_PRIMARY_RESULT="$FAIL (prerequisite framework build failed)"
  U1_RESULT="N/A (skipped)"
  U2_RESULT="N/A (skipped)"
  U3_RESULT="N/A (skipped)"
fi

# ── U-SWIFT default-U3 note: also test WITHOUT -Xcc -isysroot ────────────────
# (Only when primary already passed — confirms which flags are NOT needed.)
if [[ "$SWIFT_PRIMARY_RESULT" == "$PASS"* && "$U3_RESULT" == "N/A" ]]; then
  U3_RESULT="NOT_NEEDED (build succeeded without -Xcc -isysroot)"
fi

# ── U4: Verify arm64 Mach-O ──────────────────────────────────────────────────
echo ""
echo "===== U4: Verify Runner is arm64 Mach-O ====="
if [[ -f "$OUTDIR/Runner" ]]; then
  FILE_OUT=$(file "$OUTDIR/Runner")
  echo "file: $FILE_OUT"
  if echo "$FILE_OUT" | grep -Eqi "arm64|aarch64"; then
    U4_RESULT="$PASS (arm64 Mach-O confirmed)"
    echo "U4: $PASS"
  else
    U4_RESULT="$FAIL (not arm64: $FILE_OUT)"
    echo "U4: $FAIL — $FILE_OUT"
  fi

  # Additional: dump load commands via llvm-objdump or readelf.
  echo ""
  echo "Load commands (llvm-objdump -p, if available):"
  if command -v llvm-objdump &>/dev/null; then
    llvm-objdump -p "$OUTDIR/Runner" 2>&1 | head -60 || true
  elif command -v objdump &>/dev/null; then
    objdump -p "$OUTDIR/Runner" 2>&1 | head -60 || true
  else
    echo "(llvm-objdump not found — skipping load-command dump)"
  fi

  # Confirm symbols reference SharedLogic + SwiftUI.
  echo ""
  echo "Symbol check (llvm-nm / nm):"
  NM_BIN=""
  for _nm in llvm-nm nm; do
    if command -v "$_nm" &>/dev/null; then NM_BIN="$_nm"; break; fi
  done
  if [[ -n "$NM_BIN" ]]; then
    "$NM_BIN" -D "$OUTDIR/Runner" 2>/dev/null \
      | grep -iE 'SharedLogic|SwiftUI|swift_' | head -20 || true
  else
    echo "(no nm found)"
  fi
else
  U4_RESULT="$FAIL (Runner binary not found at $OUTDIR/Runner)"
  echo "U4: $FAIL — Runner not produced"
fi

# ── U5: @rpath/libswift load commands ────────────────────────────────────────
echo ""
echo "===== U5: @rpath/libswift*.dylib load commands (SwiftSupport need) ====="
if [[ -f "$OUTDIR/Runner" ]]; then
  LIBSWIFT_REFS=""
  if command -v llvm-objdump &>/dev/null; then
    LIBSWIFT_REFS=$(llvm-objdump -p "$OUTDIR/Runner" 2>/dev/null \
      | grep '@rpath/libswift' || true)
  elif command -v objdump &>/dev/null; then
    LIBSWIFT_REFS=$(objdump -p "$OUTDIR/Runner" 2>/dev/null \
      | grep '@rpath/libswift' || true)
  fi

  if [[ -n "$LIBSWIFT_REFS" ]]; then
    echo "⚠️  WARNING: Runner hard-requires bundled Swift runtime:"
    echo "$LIBSWIFT_REFS"
    echo ""
    echo "  This means a SwiftSupport/ directory embedding these dylibs is required"
    echo "  for App Store / OTA distribution. For sideload via xcross/xtool the device"
    echo "  OS ships the Swift runtime so it MAY work without SwiftSupport/, but IPA"
    echo "  submission will fail. The packer must either:"
    echo "    a) Copy Swift runtime dylibs into SwiftSupport/ of the IPA, OR"
    echo "    b) Link with -static-stdlib (if supported for iOS) to avoid @rpath refs."
    U5_RESULT="WARN (@rpath/libswift refs present — SwiftSupport/ may be needed)"
  else
    echo "No @rpath/libswift refs found — SwiftSupport/ not required."
    U5_RESULT="$PASS (no @rpath/libswift refs — statically linked or not present)"
  fi
else
  U5_RESULT="N/A (Runner not produced)"
fi

# ── SPIKE SUMMARY ─────────────────────────────────────────────────────────────
echo ""
echo "========================================================"
echo "SPIKE SUMMARY — swift-runner-spike.sh"
echo "========================================================"
echo "SharedLogic.framework build: $FWK_RESULT"
echo "swiftc Runner build:         $SWIFT_PRIMARY_RESULT"
echo "  U1 (-use-ld= flag):        $U1_RESULT"
echo "  U2 (SwiftUI import):       $U2_RESULT"
echo "  U3 (-Xcc -isysroot):       $U3_RESULT"
echo "  U4 (arm64 Mach-O):         $U4_RESULT"
echo "  U5 (@rpath/libswift):      $U5_RESULT"
echo "--------------------------------------------------------"
if [[ -n "$WORKING_SWIFTC_CMD" ]]; then
  echo "EXACT WORKING swiftc invocation (lock into packer):"
  echo ""
  echo "  $WORKING_SWIFTC_CMD"
  echo ""
else
  echo "NO WORKING swiftc invocation found — check logs above."
fi
echo "--------------------------------------------------------"
echo "JAR_PATCHED=$JAR_PATCHED"
echo "  → HostManager jar patch is a hard prerequisite for konanc ios_arm64."
echo "    Without it konanc returns 'target ios_arm64 is not available'."
echo "========================================================"
echo ""
echo "⚠️  IMPORTANT: Run this script INSIDE the xcross-compose amd64 container"
echo "   (or equivalent linux/amd64 host with swift 6.x) BEFORE trusting"
echo "   the swiftc flags printed above for inclusion in the packer."
echo "   Results on a different host may differ."
# Exit 0 so any caller can upload logs/artifacts even on failure.
exit 0
