import 'dart:convert';
import 'dart:io';

import 'package:args/command_runner.dart';
import 'package:path/path.dart' as p;
import 'package:xcross/src/util/logging.dart';

/// `xcross vscode` — write the `.vscode/` files that make the editor's Run &
/// Debug / Restart / Hot Reload buttons drive `xcross flutter run`.
class VscodeCommand extends Command<void> {
  @override
  String get name => 'vscode';

  @override
  String get description =>
      'Set up .vscode/ so F5, Restart and Hot Reload run on an iOS device.';

  @override
  Future<void> run() async {
    final dir = Directory(p.join(Directory.current.path, '.vscode'));
    await dir.create(recursive: true);

    // Always ours to overwrite, and it embeds the absolute xcross path captured
    // now so a changed PATH can't break the editor later.
    final exe = Platform.resolvedExecutable;
    if (p.basenameWithoutExtension(exe) != 'xcross') {
      Log.logWarn('embedding $exe — run `xcross vscode` from the installed '
          'binary, not `dart run`, or F5 will not work');
    }
    final shim = File(p.join(dir.path, 'xcross_dap.dart'));
    await shim.writeAsString(
      // The shim is a non-raw Dart string literal, so `$` in a path must be
      // escaped too — jsonEncode does not.
      _shim.replaceAll('<XCROSS>', jsonEncode(exe).replaceAll(r'$', r'\$')),
    );
    Log.logDone('Wrote ${p.relative(shim.path)}');

    // launch.json / settings.json are JSONC in the wild; a comment-preserving
    // merge is 200 lines of nothing, so print the snippet instead.
    await _writeIfAbsent(p.join(dir.path, 'launch.json'), _launchJson);
    await _writeIfAbsent(p.join(dir.path, 'settings.json'), _settingsJson);

    Log.logInfo(
        'Next',
        Log.ansi.subtle('open the project in VS Code and press F5, '
            "then 'Hot Reload' / 'Restart' in the debug toolbar"));
  }

  static Future<void> _writeIfAbsent(String path, String content) async {
    final file = File(path);
    if (file.existsSync()) {
      Log.logWarn('${p.relative(path)} already exists — merge this in yourself:\n'
          '$content');
      return;
    }
    await file.writeAsString(content);
    Log.logDone('Wrote ${p.relative(path)}');
  }
}

const String _launchJson = r'''
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "xcross: iOS device",
      "type": "dart",
      "request": "attach",
      "debuggerType": "flutter",
      "program": "lib/main.dart",
      // VS Code sets no cwd on the adapter process, so state it here rather
      // than depending on a Dart-Code default.
      "cwd": "${workspaceFolder}",
      // Passed straight to `xcross flutter run`. With more than one iPhone
      // connected, select one: ["--udid", "<UDID>"].
      "args": []
    }
  ]
}
''';

const String _settingsJson = '''
{
  "dart.customFlutterDapPath": ".vscode/xcross_dap.dart",
  "dart.promptToRunIfErrors": false
}
''';

/// Dart-Code spawns this as `dart <this file> debug_adapter`, so it must stay a
/// source file (the Dart VM cannot run xcross's AOT snapshot) and must write
/// NOTHING to stdout — that pipe carries DAP frames.
const String _shim = r'''
// GENERATED by `xcross vscode`. Do not edit — re-run the command instead.
import 'dart:io';

Future<void> main(List<String> args) async {
  // `flutter test` sessions arrive through the same customFlutterDapPath
  // setting; hand those to the real Flutter adapter.
  if (args.contains('--test')) {
    final flutterRoot = Platform.environment['FLUTTER_ROOT'];
    if (flutterRoot == null) {
      stderr.writeln('xcross_dap: FLUTTER_ROOT is not set; '
          'cannot delegate a flutter test session.');
      exit(2);
    }
    final flutter = await Process.start(
      '$flutterRoot/bin/flutter',
      ['debug-adapter', ...args.where((a) => a != 'debug_adapter')],
      mode: ProcessStartMode.inheritStdio,
    );
    exit(await flutter.exitCode);
  }

  try {
    final dap = await Process.start(
      <XCROSS>,
      ['dap'],
      mode: ProcessStartMode.inheritStdio,
    );
    exit(await dap.exitCode);
  } on ProcessException catch (e) {
    stderr.writeln('xcross_dap: could not start xcross: ${e.message}\n'
        'Reinstall xcross, then re-run `xcross vscode`.');
    exit(2);
  }
}
''';
