import 'dart:convert';
import 'dart:io';

import 'package:args/command_runner.dart';
import 'package:cli_kit/cli_kit.dart';
import 'package:path/path.dart' as p;
import 'package:xcross/src/cli/ide/subcommands/vscode_json_merge.dart';
import 'package:xcross/src/util/errors.dart';

/// `xcross ide vscode` — write / upsert `.vscode/` so Run & Debug / Restart /
/// Hot Reload drive `xcross flutter run`.
class VscodeCommand extends Command<void> {
  @override
  String get name => 'vscode';

  @override
  String get description =>
      'Set up .vscode/ so F5, Restart and Hot Reload run on an iOS device.';

  @override
  Future<void> run() async {
    final dir = Directory(p.join(Directory.current.path, '.vscode'));
    await dir.create(recursive: true);

    // Always ours to overwrite, and it embeds the absolute xcross path captured
    // now so a changed PATH can't break the editor later.
    final exe = Platform.resolvedExecutable;
    if (p.basenameWithoutExtension(exe) != 'xcross') {
      Log.logWarn(
        'embedding $exe — run `xcross ide vscode` from the installed '
        'binary, not `dart run`, or F5 will not work',
      );
    }
    final shim = File(p.join(dir.path, 'xcross_dap.dart'));
    await shim.writeAsString(
      // The shim is a non-raw Dart string literal, so `$` in a path must be
      // escaped too — jsonEncode does not.
      _shim.replaceAll('<XCROSS>', jsonEncode(exe).replaceAll(r'$', r'\$')),
    );
    Log.logDone('Wrote ${p.relative(shim.path)}');

    await upsertJsonFile(p.join(dir.path, 'launch.json'), mergeLaunchDoc);
    await upsertJsonFile(p.join(dir.path, 'settings.json'), mergeSettingsDoc);

    Log.logInfo(
      'Next',
      Log.ansi.subtle(
        'open the project in VS Code and press F5, '
        "then 'Hot Reload' / 'Restart' in the debug toolbar",
      ),
    );
  }
}

/// Read-merge-write a JSON/JSONC file. Skips the write when already current.
Future<void> upsertJsonFile(
  String path,
  Map<String, Object?> Function(Map<String, Object?>? existing) merge,
) async {
  final file = File(path);
  Map<String, Object?>? existing;
  if (file.existsSync()) {
    final raw = await file.readAsString();
    if (raw.trim().isNotEmpty) {
      late final Object? decoded;
      try {
        decoded = parseJsonc(raw);
      } on FormatException catch (e) {
        throw XcrossError(
          '${p.relative(path)} is not valid JSON/JSONC (${e.message}) — '
          'fix it, then re-run `xcross ide vscode`',
        );
      }
      if (decoded is! Map) {
        throw XcrossError(
          '${p.relative(path)} must be a JSON object — '
          'fix it, then re-run `xcross ide vscode`',
        );
      }
      existing = <String, Object?>{
        for (final e in decoded.entries) '${e.key}': e.value,
      };
    }
  }

  final merged = merge(existing);
  if (existing != null && jsonDeepEqual(existing, merged)) {
    Log.logDone('Unchanged ${p.relative(path)}');
    return;
  }
  await file.writeAsString(encodePrettyJson(merged));
  Log.logDone(
    existing == null
        ? 'Wrote ${p.relative(path)}'
        : 'Updated ${p.relative(path)}',
  );
}

/// Dart-Code spawns this as `dart <this file> debug_adapter`, so it must stay a
/// source file (the Dart VM cannot run xcross's AOT snapshot) and must write
/// NOTHING to stdout — that pipe carries DAP frames.
const String _shim = r'''
// GENERATED by `xcross ide vscode`. Do not edit — re-run the command instead.
import 'dart:io';

Future<void> main(List<String> args) async {
  // `flutter test` sessions arrive through the same customFlutterDapPath
  // setting; hand those to the real Flutter adapter. Non-xcross launch
  // configs are gated inside `xcross flutter dap` via `"xcross": true`.
  if (args.contains('--test')) {
    final flutterRoot = Platform.environment['FLUTTER_ROOT'];
    if (flutterRoot == null) {
      stderr.writeln('xcross_dap: FLUTTER_ROOT is not set; '
          'cannot delegate a flutter test session.');
      exit(2);
    }
    final flutter = await Process.start(
      '$flutterRoot/bin/flutter',
      ['debug-adapter', ...args.where((a) => a != 'debug_adapter')],
      mode: ProcessStartMode.inheritStdio,
    );
    exit(await flutter.exitCode);
  }

  try {
    final dap = await Process.start(
      <XCROSS>,
      ['flutter', 'dap'],
      mode: ProcessStartMode.inheritStdio,
    );
    exit(await dap.exitCode);
  } on ProcessException catch (e) {
    stderr.writeln('xcross_dap: could not start xcross: ${e.message}\n'
        'Reinstall xcross, then re-run `xcross ide vscode`.');
    exit(2);
  }
}
''';
