/// Flutter iOS packing and hot reload, internal to xcross.
library;

export 'package:xcross/src/host/shared/flutter/flutter_sdk_host_policy.dart';
export 'package:xcross/src/host/shared/flutter/posix_flutter_sdk_policy.dart';
export 'package:xcross/src/shared/flutter/extensions/app_extension_plist.dart';
export 'package:xcross/src/shared/flutter/extensions/app_extension_resources.dart';
export 'package:xcross/src/shared/flutter/flutter_assets_compiler.dart';
export 'package:xcross/src/shared/flutter/flutter_build_options_resolver.dart';
export 'package:xcross/src/shared/flutter/flutter_build_runtime.dart';
export 'package:xcross/src/shared/flutter/flutter_build_steps.dart';
export 'package:xcross/src/shared/flutter/flutter_bundle_assembler.dart';
export 'package:xcross/src/shared/flutter/flutter_kernel_compiler.dart';
export 'package:xcross/src/shared/flutter/flutter_project_resolver.dart';
export 'package:xcross/src/shared/flutter/project/dart_defines_reader.dart';
export 'package:xcross/src/shared/flutter/project/ios_bundle_versions_resolver.dart';
export 'package:xcross/src/shared/flutter/project/ios_deployment_target_resolver.dart';
export 'package:xcross/src/shared/flutter/project/pbx_project_reader.dart';
export 'package:xcross/src/shared/flutter/project/pubspec_info_reader.dart';
export 'package:xcross/src/shared/flutter/vm_service_connector.dart';
export 'package:xcross/src/shared/models/pack_result.dart';
export 'package:xcross/src/target/shared/flutter/flutter_target_build_policy.dart';

export 'build/flutter_debug_bundler.dart';
export 'build/flutter_pack_operation.dart';
export 'build/flutter_packer.dart';
export 'build/hot_reload_setup.dart';
export 'build/info_plist.dart';
export 'build/ios_bundle_id.dart';
export 'build/ios_engine_cache.dart';
export 'build/ios_plugin_package.dart';
export 'build/ios_plugins.dart';
export 'build/macho_dylib_rewriter.dart';
export 'build/runner_shim.dart';
export 'constants.dart';
export 'errors.dart';
export 'hot_reload/dart_vm_service_client.dart';
export 'hot_reload/hot_reload_controller.dart';
export 'hot_reload/source_watcher.dart';
export 'hot_reload/vm_service_output.dart';
export 'models/flutter/dart_defines.dart';
export 'models/flutter/flutter_build_options.dart';
export 'models/hot_reload_config.dart';
export 'models/pubspec_info.dart';
