import 'package:meta/meta.dart';

@internal
const appleDeveloperKitTestsRoles = <String, Map<String, String>>{
  'workspace:packages/apple_developer_kit/hook/build.dart': {
    'FUNCTION:_buildWithSystemCc': 'private',
    'FUNCTION:_resolveSystemCc': 'private',
    'FUNCTION:main': 'entrypoint',
    'FUNCTION:posixHostMappingHeader': 'internal',
    'FUNCTION:resolveMacOSCompiler': 'internal',
    'FUNCTION:systemCompilerFlags': 'internal',
    'FUNCTION:windowsBridgeSources': 'internal',
    'TOP_LEVEL_VARIABLE:_assetName': 'private',
  },
  'workspace:packages/apple_developer_kit/test/adi/adi_client_test.dart': {
    'FUNCTION:main': 'entrypoint',
  },
  'workspace:packages/apple_developer_kit/test/adi/adi_client_windows_test.dart':
      {'FUNCTION:main': 'entrypoint'},
  'workspace:packages/apple_developer_kit/test/adi/apk_fetch_test.dart': {
    'CLASS:RecordingApkClient': 'internal',
    'FUNCTION:main': 'entrypoint',
  },
  'workspace:packages/apple_developer_kit/test/adi/build_hook_test.dart': {
    'FUNCTION:main': 'entrypoint',
    'TOP_LEVEL_VARIABLE:_packageRoot': 'private',
  },
  'workspace:packages/apple_developer_kit/test/adi/elf_loader_test.dart': {
    'CLASS:RecordingAllocator': 'internal',
    'FUNCTION:main': 'entrypoint',
  },
  'workspace:packages/apple_developer_kit/test/adi/linux_abi_layout_test.dart':
      {'FUNCTION:main': 'entrypoint'},
  'workspace:packages/apple_developer_kit/test/adi/native_library_loader_aot_test.dart':
      {'FUNCTION:main': 'entrypoint'},
  'workspace:packages/apple_developer_kit/test/adi/native_asset_id_test.dart': {
    'FUNCTION:main': 'entrypoint',
    'TOP_LEVEL_VARIABLE:_packageRoot': 'private',
  },
  'workspace:packages/apple_developer_kit/test/adi/posix_bridge_test.dart': {
    'FUNCTION:main': 'entrypoint',
    'FUNCTION:symbol': 'internal',
  },
  'workspace:packages/apple_developer_kit/test/adi/support/elf_fixture.dart': {
    'CLASS:CallbackElfCodePreparation': 'internal',
    'FUNCTION:elfFixture': 'internal',
  },
  'workspace:packages/apple_developer_kit/test/adi/windows_abi_test.dart': {
    'FUNCTION:main': 'entrypoint',
  },
  'workspace:packages/apple_developer_kit/test/adi/windows_arm64_bridge_test.dart':
      {
        'FUNCTION:_code': 'private',
        'FUNCTION:_integerProbe': 'private',
        'FUNCTION:main': 'entrypoint',
        'TOP_LEVEL_VARIABLE:_callWithShadowStack': 'private',
        'TOP_LEVEL_VARIABLE:_readX18': 'private',
        'TOP_LEVEL_VARIABLE:_return': 'private',
      },
  'workspace:packages/apple_developer_kit/test/apple_http_client_test.dart': {
    'CLASS:RecordingHttpClient': 'internal',
    'FUNCTION:main': 'entrypoint',
  },
  'workspace:packages/apple_developer_kit/test/apple_rate_limit_test.dart': {
    'FUNCTION:main': 'entrypoint',
  },
  'workspace:packages/apple_developer_kit/test/appstoreconnect/appstoreconnect_test.dart':
      {
        'CLASS:FakeProvisioningClient': 'internal',
        'FUNCTION:main': 'entrypoint',
      },
  'workspace:packages/apple_developer_kit/test/appstoreconnect/asc_client_test.dart':
      {'FUNCTION:main': 'entrypoint'},
  'workspace:packages/apple_developer_kit/test/appstoreconnect/asc_jwt_test.dart':
      {'FUNCTION:main': 'entrypoint'},
  'workspace:packages/apple_developer_kit/test/appstoreconnect/developer_services_client_test.dart':
      {
        'CLASS:TrackingTeamHttpClient': 'internal',
        'FUNCTION:_deviceJson': 'private',
        'FUNCTION:_token': 'private',
        'FUNCTION:main': 'entrypoint',
      },
  'workspace:packages/apple_developer_kit/test/appstoreconnect/provisioning_identifiers_test.dart':
      {'FUNCTION:main': 'entrypoint'},
  'workspace:packages/apple_developer_kit/test/grandslam/anisette/anisette_data_provider_test.dart':
      {
        'CLASS:FakeAdiProvisioning': 'internal',
        'CLASS:RefusingAdiProvisioning': 'internal',
        'CLASS:RejectingBoundaryLoader': 'internal',
        'FUNCTION:_bytes': 'private',
        'FUNCTION:_gsaResponsePlist': 'private',
        'FUNCTION:_lookupResponsePlist': 'private',
        'FUNCTION:main': 'entrypoint',
        'TOP_LEVEL_VARIABLE:_lookupUrl': 'private',
        'TOP_LEVEL_VARIABLE:_midFinishUrl': 'private',
        'TOP_LEVEL_VARIABLE:_midStartUrl': 'private',
      },
  'workspace:packages/apple_developer_kit/test/grandslam/anisette/anisette_state_test.dart':
      {'FUNCTION:main': 'entrypoint'},
  'workspace:packages/apple_developer_kit/test/grandslam/anisette/grandslam_endpoints_test.dart':
      {
        'FUNCTION:main': 'entrypoint',
        'TOP_LEVEL_VARIABLE:_lookupResponsePlist': 'private',
      },
  'workspace:packages/apple_developer_kit/test/grandslam/anisette/grandslam_transport_live_test.dart':
      {'CLASS:CountingConnections': 'internal', 'FUNCTION:main': 'entrypoint'},
  'workspace:packages/apple_developer_kit/test/grandslam/app_token_exchange_test.dart':
      {
        'FUNCTION:_bytes': 'private',
        'FUNCTION:_encryptBlob': 'private',
        'FUNCTION:_hex': 'private',
        'FUNCTION:main': 'entrypoint',
        'TOP_LEVEL_VARIABLE:_endpoints': 'private',
        'TOP_LEVEL_VARIABLE:_gsServiceUrl': 'private',
      },
  'workspace:packages/apple_developer_kit/test/grandslam/grandslam_login_test.dart':
      {
        'CLASS:FakeGsaServer': 'internal',
        'CLASS:SrpVerifyResult': 'internal',
        'FUNCTION:_bd': 'private',
        'FUNCTION:_bigIntToBytes': 'private',
        'FUNCTION:_bytesOf': 'private',
        'FUNCTION:_bytesToBigInt': 'private',
        'FUNCTION:_calcXY': 'private',
        'FUNCTION:_computeX': 'private',
        'FUNCTION:_constantTimeEquals': 'private',
        'FUNCTION:_encryptCbc': 'private',
        'FUNCTION:_fakeAnisetteHeaders': 'private',
        'FUNCTION:_hmacSha256': 'private',
        'FUNCTION:_negProto': 'private',
        'FUNCTION:_operationResponse': 'private',
        'FUNCTION:_padLeft': 'private',
        'FUNCTION:_randomBytes': 'private',
        'FUNCTION:_sessionSubkey': 'private',
        'FUNCTION:main': 'entrypoint',
        'TOP_LEVEL_VARIABLE:_g': 'private',
        'TOP_LEVEL_VARIABLE:_gsServiceUrl': 'private',
        'TOP_LEVEL_VARIABLE:_n': 'private',
        'TOP_LEVEL_VARIABLE:_nByteLength': 'private',
        'TOP_LEVEL_VARIABLE:_smsPutUrl': 'private',
        'TOP_LEVEL_VARIABLE:_smsValidateUrl': 'private',
        'TOP_LEVEL_VARIABLE:_testEndpoints': 'private',
        'TOP_LEVEL_VARIABLE:_trustedDeviceUrl': 'private',
        'TOP_LEVEL_VARIABLE:_validateCodeUrl': 'private',
      },
  'workspace:packages/apple_developer_kit/test/grandslam/grandslam_response_test.dart':
      {'FUNCTION:main': 'entrypoint'},
  'workspace:packages/apple_developer_kit/test/grandslam/grandslam_session_store_test.dart':
      {'FUNCTION:main': 'entrypoint'},
  'workspace:packages/apple_developer_kit/test/grandslam/srp_client_test.dart':
      {
        'FUNCTION:_bigIntToBytes': 'private',
        'FUNCTION:_bytesToBigInt': 'private',
        'FUNCTION:_bytesToHex': 'private',
        'FUNCTION:_calcXYIndependently': 'private',
        'FUNCTION:_computeXIndependently': 'private',
        'FUNCTION:_padLeft': 'private',
        'FUNCTION:_randomBigInt': 'private',
        'FUNCTION:_randomBytes': 'private',
        'FUNCTION:main': 'entrypoint',
        'TOP_LEVEL_VARIABLE:_g': 'private',
        'TOP_LEVEL_VARIABLE:_n': 'private',
        'TOP_LEVEL_VARIABLE:_nByteLength': 'private',
      },
  'workspace:packages/apple_developer_kit/test/host/apple_host_test.dart': {
    'CLASS:Identity': 'internal',
    'CLASS:IdentityRunner': 'internal',
    'CLASS:PermissionPolicyFileSystem': 'internal',
    'CLASS:Permissions': 'internal',
    'CLASS:RecordingLibrary': 'internal',
    'CLASS:SecureWriteFile': 'internal',
    'CLASS:SecureWriteFileSystem': 'internal',
    'CLASS:SecureWritePermissions': 'internal',
    'FUNCTION:main': 'entrypoint',
  },
  'workspace:packages/apple_developer_kit/test/secure/local_cipher_test.dart': {
    'FUNCTION:main': 'entrypoint',
  },
  'workspace:packages/apple_developer_kit/test/signing/bundle_signer_test.dart':
      {
        'FUNCTION:_algorithmIdentifier': 'private',
        'FUNCTION:_app': 'private',
        'FUNCTION:_appExtension': 'private',
        'FUNCTION:_base128': 'private',
        'FUNCTION:_bytes': 'private',
        'FUNCTION:_entitlements': 'private',
        'FUNCTION:_framework': 'private',
        'FUNCTION:_integer': 'private',
        'FUNCTION:_link': 'private',
        'FUNCTION:_macho': 'private',
        'FUNCTION:_map': 'private',
        'FUNCTION:_name': 'private',
        'FUNCTION:_oid': 'private',
        'FUNCTION:_plist': 'private',
        'FUNCTION:_sequence': 'private',
        'FUNCTION:_set': 'private',
        'FUNCTION:_setU32le': 'private',
        'FUNCTION:_setU64le': 'private',
        'FUNCTION:_signatureSlots': 'private',
        'FUNCTION:_signingAsset': 'private',
        'FUNCTION:_tlv': 'private',
        'FUNCTION:_u32be': 'private',
        'FUNCTION:_u32le': 'private',
        'FUNCTION:_writeInfo': 'private',
        'FUNCTION:main': 'entrypoint',
        'TOP_LEVEL_VARIABLE:_mhDylib': 'private',
        'TOP_LEVEL_VARIABLE:_mhExecute': 'private',
      },
  'workspace:packages/apple_developer_kit/test/signing/code_resources_test.dart':
      {'FUNCTION:main': 'entrypoint'},
  'workspace:packages/apple_developer_kit/test/signing/macho_signer_test.dart':
      {
        'CLASS:RejectingPreservePermissions': 'internal',
        'FUNCTION:_algorithmIdentifier': 'private',
        'FUNCTION:_align': 'private',
        'FUNCTION:_base128': 'private',
        'FUNCTION:_codeSignatureCommand': 'private',
        'FUNCTION:_containsBytes': 'private',
        'FUNCTION:_cstring': 'private',
        'FUNCTION:_entitlements': 'private',
        'FUNCTION:_integer': 'private',
        'FUNCTION:_macho': 'private',
        'FUNCTION:_name': 'private',
        'FUNCTION:_oid': 'private',
        'FUNCTION:_sequence': 'private',
        'FUNCTION:_set': 'private',
        'FUNCTION:_setU32le': 'private',
        'FUNCTION:_setU64le': 'private',
        'FUNCTION:_signatureSlots': 'private',
        'FUNCTION:_signingAsset': 'private',
        'FUNCTION:_tlv': 'private',
        'FUNCTION:_u32be': 'private',
        'FUNCTION:_u32le': 'private',
        'FUNCTION:_u64be': 'private',
        'FUNCTION:_u64le': 'private',
        'FUNCTION:_withU32': 'private',
        'FUNCTION:main': 'entrypoint',
        'TOP_LEVEL_VARIABLE:_mhDylib': 'private',
        'TOP_LEVEL_VARIABLE:_mhExecute': 'private',
      },
  'workspace:packages/apple_developer_kit/test/signing/signing_asset_test.dart':
      {
        'CLASS:TestReader': 'internal',
        'CLASS:TestValue': 'internal',
        'FUNCTION:_algorithmIdentifier': 'private',
        'FUNCTION:_base128': 'private',
        'FUNCTION:_certificateFixture': 'private',
        'FUNCTION:_certificateSubject': 'private',
        'FUNCTION:_compareBytes': 'private',
        'FUNCTION:_concat': 'private',
        'FUNCTION:_integer': 'private',
        'FUNCTION:_octet': 'private',
        'FUNCTION:_oid': 'private',
        'FUNCTION:_oidValue': 'private',
        'FUNCTION:_profileCms': 'private',
        'FUNCTION:_replaceCertificateIssuer': 'private',
        'FUNCTION:_sequence': 'private',
        'FUNCTION:_set': 'private',
        'FUNCTION:_single': 'private',
        'FUNCTION:_sortedContent': 'private',
        'FUNCTION:_tlv': 'private',
        'FUNCTION:_writeFixture': 'private',
        'FUNCTION:main': 'entrypoint',
        'TOP_LEVEL_VARIABLE:_oidAppleCdHashes': 'private',
        'TOP_LEVEL_VARIABLE:_oidAppleCdHashes2': 'private',
        'TOP_LEVEL_VARIABLE:_oidContentType': 'private',
        'TOP_LEVEL_VARIABLE:_oidData': 'private',
        'TOP_LEVEL_VARIABLE:_oidMessageDigest': 'private',
        'TOP_LEVEL_VARIABLE:_oidSha256': 'private',
        'TOP_LEVEL_VARIABLE:_oidSignedData': 'private',
        'TOP_LEVEL_VARIABLE:_oidSigningTime': 'private',
      },
  'workspace:packages/apple_developer_kit/test/support/host_services.dart': {
    'CLASS:InertElfLibrary': 'internal',
    'CLASS:RecordingPathLibrary': 'internal',
    'CLASS:SilentLogOutput': 'internal',
    'CLASS:UnusedNativeLoader': 'internal',
    'FUNCTION:testMacOSAppleHostServices': 'internal',
    'FUNCTION:testNativeLoader': 'internal',
    'FUNCTION:testPosixAllocator': 'internal',
    'FUNCTION:testWindowsAppleHostServices': 'internal',
    'GETTER:testHostServices': 'internal',
  },
  'workspace:packages/apple_developer_kit/test/support/mapped_apple_fixture.dart':
      {
        'CLASS:FixedAppleMachineIdentity': 'internal',
        'CLASS:MappedAppleFileSystem': 'internal',
        'CLASS:MappedAppleFixture': 'internal',
        'CLASS:MappedAppleHost': 'internal',
        'CLASS:MappedApplePaths': 'internal',
        'CLASS:RecordingApplePermissions': 'internal',
      },
};
