import 'package:meta/meta.dart';

@internal
const xcrossComposeTestsRoles = <String, Map<String, String>>{
  'workspace:packages/xcross/test/compose/compose_app_assembler_test.dart': {
    'CLASS:ComposeFixture': 'internal',
    'FUNCTION:_packageConfig': 'private',
    'FUNCTION:main': 'entrypoint',
  },
  'workspace:packages/xcross/test/compose/compose_entitlements_test.dart': {
    'FUNCTION:main': 'entrypoint',
  },
  'workspace:packages/xcross/test/compose/compose_host_test.dart': {
    'FUNCTION:main': 'entrypoint',
  },
  'workspace:packages/xcross/test/compose/compose_info_plist_test.dart': {
    'CLASS:ComposeFixture': 'internal',
    'FUNCTION:main': 'entrypoint',
    'TOP_LEVEL_VARIABLE:_repoRoot': 'private',
  },
  'workspace:packages/xcross/test/compose/compose_nested_ios_app_test.dart': {
    'FUNCTION:main': 'entrypoint',
  },
  'workspace:packages/xcross/test/compose/compose_pack_operation_test.dart': {
    'FUNCTION:_packer': 'private',
    'FUNCTION:_project': 'private',
    'FUNCTION:_toolchain': 'private',
    'FUNCTION:main': 'entrypoint',
  },
  'workspace:packages/xcross/test/compose/compose_toolchain_test.dart': {
    'CLASS:FakeDarwinSdk': 'internal',
    'FUNCTION:_installerThatBuildsNewCache': 'private',
    'FUNCTION:_matchingSha256': 'private',
    'FUNCTION:_resolverWithPreflight': 'private',
    'FUNCTION:_snapshotDirectory': 'private',
    'FUNCTION:_writeCompleteMarker': 'private',
    'FUNCTION:_writeValidCache': 'private',
    'FUNCTION:main': 'entrypoint',
  },
  'workspace:packages/xcross/test/compose/compose_watch_session_test.dart': {
    'FUNCTION:main': 'entrypoint',
  },
  'workspace:packages/xcross/test/compose/framework_build_stamp_test.dart': {
    'FUNCTION:main': 'entrypoint',
  },
  'workspace:packages/xcross/test/compose/gradle_klib_builder_test.dart': {
    'CLASS:ComposeCall': 'internal',
    'CLASS:ComposeFixture': 'internal',
    'FUNCTION:_unpackedKlib': 'private',
    'FUNCTION:main': 'entrypoint',
  },
  'workspace:packages/xcross/test/compose/host_manager_patcher_test.dart': {
    'FUNCTION:main': 'entrypoint',
    'TOP_LEVEL_VARIABLE:aload0': 'internal',
    'TOP_LEVEL_VARIABLE:areturn': 'internal',
    'TOP_LEVEL_VARIABLE:iconst1': 'internal',
    'TOP_LEVEL_VARIABLE:invokeSpecial': 'internal',
    'TOP_LEVEL_VARIABLE:invokeVirtual': 'internal',
    'TOP_LEVEL_VARIABLE:ireturn': 'internal',
    'TOP_LEVEL_VARIABLE:vreturn': 'internal',
  },
  'workspace:packages/xcross/test/compose/ios_app_config_test.dart': {
    'FUNCTION:main': 'entrypoint',
  },
  'workspace:packages/xcross/test/compose/kmp_project_test.dart': {
    'FUNCTION:_fixture': 'private',
    'FUNCTION:_framework': 'private',
    'FUNCTION:_kotlinEntry': 'private',
    'FUNCTION:_rawBuildScript': 'private',
    'FUNCTION:_settings': 'private',
    'FUNCTION:_swift': 'private',
    'FUNCTION:_xcconfig': 'private',
    'FUNCTION:main': 'entrypoint',
    'TOP_LEVEL_VARIABLE:_repoRoot': 'private',
  },
  'workspace:packages/xcross/test/compose/konan_configuration_test.dart': {
    'CLASS:ComposeFixture': 'internal',
    'FUNCTION:_slash': 'private',
    'FUNCTION:main': 'entrypoint',
  },
  'workspace:packages/xcross/test/compose/kotlin_framework_builder_test.dart': {
    'CLASS:ComposeCall': 'internal',
    'CLASS:ComposeFixture': 'internal',
    'FUNCTION:main': 'entrypoint',
  },
  'workspace:packages/xcross/test/compose/kotlin_native_caches_test.dart': {
    'CLASS:ComposeFixture': 'internal',
    'FUNCTION:_produceCache': 'private',
    'FUNCTION:_unpackedKlib': 'private',
    'FUNCTION:main': 'entrypoint',
  },
  'workspace:packages/xcross/test/compose/kotlin_source_watcher_test.dart': {
    'FUNCTION:main': 'entrypoint',
  },
  'workspace:packages/xcross/test/compose/runner_builder_test.dart': {
    'CLASS:ComposeCall': 'internal',
    'CLASS:ComposeFixture': 'internal',
    'CLASS:MachOOutput': 'internal',
    'FUNCTION:_machoBytes': 'private',
    'FUNCTION:main': 'entrypoint',
    'TOP_LEVEL_VARIABLE:_invalidMachOOutputs': 'private',
    'TOP_LEVEL_VARIABLE:_validMachOOutputs': 'private',
  },
  'workspace:packages/xcross/test/compose/support/class_file_builder.dart': {
    'FUNCTION:codeAttr': 'internal',
    'FUNCTION:codeBody': 'internal',
    'FUNCTION:cpClass': 'internal',
    'FUNCTION:cpDouble': 'internal',
    'FUNCTION:cpLong': 'internal',
    'FUNCTION:cpMethodref': 'internal',
    'FUNCTION:cpNameAndType': 'internal',
    'FUNCTION:cpSection': 'internal',
    'FUNCTION:cpUtf8': 'internal',
    'FUNCTION:member': 'internal',
    'FUNCTION:u2': 'internal',
    'FUNCTION:u4': 'internal',
    'TOP_LEVEL_VARIABLE:classFileHeader': 'internal',
  },
  'workspace:packages/xcross/test/compose/support/class_file_inspector.dart': {
    'CLASS:InspectedClass': 'internal',
    'FUNCTION:_walkCp': 'private',
    'FUNCTION:findLastCodeByte': 'internal',
    'FUNCTION:lastMethodCodeBody': 'internal',
    'FUNCTION:parseForInspection': 'internal',
    'FUNCTION:read16': 'internal',
    'FUNCTION:read32': 'internal',
    'FUNCTION:skipMembers': 'internal',
  },
  'workspace:packages/xcross/test/compose/support/compose_platforms.dart': {
    'CLASS:ComposeFixtureByteConsumer': 'internal',
    'CLASS:ComposeFixtureDarwinToolchainLocations': 'internal',
    'CLASS:ComposeFixtureHosts': 'internal',
    'CLASS:ComposeFixtureLogOutput': 'internal',
    'CLASS:ComposeTestSession': 'internal',
    'CLASS:FixtureSimulatorSigning': 'internal',
    'CLASS:RemappedComposeFileSystem': 'internal',
    'FUNCTION:createComposeTestSession': 'internal',
    'FUNCTION:fixtureIPhoneTargetFor': 'internal',
    'FUNCTION:fixtureSimulatorTargetFor': 'internal',
  },
  'workspace:packages/xcross/test/compose/support/fake_classes.dart': {
    'FUNCTION:_buildFakeHostManagerClass': 'private',
    'FUNCTION:buildFakeAppleConfigurablesImplClass': 'internal',
    'FUNCTION:buildFakeHostManagerClass': 'internal',
    'FUNCTION:buildFakeHostManagerClassWithDouble': 'internal',
    'FUNCTION:buildFakeObjCExportClass': 'internal',
    'FUNCTION:buildJar': 'internal',
  },
};
